w6-homework-serhatturkmen/config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'
  get 'relationships/destroy'
  get 'user_detail/:id', to: 'users#show', as: 'user_detail'
  get '/feed', to: 'users#feed', as: 'user_feed'

  resources :posts do
    patch :vote_add, on: :member
    patch :vote_reduce, on: :member
    resources :comments, controller: 'comment' do
      get '/accept/:status_id', to: 'comment#accept', as: 'accept'
    end
  end
  devise_for :users

  resources :relationships, only: [:create, :destroy]

  get '/homepage', to: 'welcome#index', as: 'welcome'
  get '/dashboard', to: 'dashboard#index', as: 'dashboard'
  root 'welcome#index'
end

w6-homework-serhatturkmen/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true

  scope :availables, -> { where(visible: true).order(created_at: :desc) }
end

w6-homework-serhatturkmen/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy vote_add vote_reduce ]
  before_action :authenticate_user!
  before_action :check_user, only: %i[edit update destroy]

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments.accepted
    @user_comment = @post.comments.where(user_id: current_user).where(status: 0)
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def vote_add
    @post.update(vote_count: @post.vote_count + 1)
    respond_to do |format|
      format.js
    end
  end

  def vote_reduce
    @post.update(vote_count: @post.vote_count - 1)
    respond_to do |format|
      format.js
    end
  end

  private

  def check_user
    unless @post.user == current_user
      respond_to do |format|
        format.html { redirect_to dashboard_path, notice: "You shall not pass." }
      end
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :content, :visible)
  end
end

w6-homework-serhatturkmen/app/helpers/posts_helper.rb
module PostsHelper
end

w6-homework-serhatturkmen/app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div class="alert alert-warning" id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group field">
    <%= form.label :title%>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group field">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="form-group form-check field">
    <%= form.check_box :visible, class: "form-check-input" %>
    <%= form.label :visible %>
  </div>

  <div class="form-group actions">
    <%= form.submit :class => 'form-control btn btn-primary' %>
  </div>
<% end %>

w6-homework-serhatturkmen/app/views/posts/_user_comment.erb
<div class="card mb-5">
  <div class="card-heading text-center p-3 border">
    <b><%= user_comments.title %></b>
    <span class="badge badge-pill badge-success float-right">Waiting for Accept</span>
  </div>
  <div class="card-body">
    <%= user_comments.content %>
  </div>
  <div class="card-footer">
    <div class="row text-center">
      <div class="col-sm-6">
        ✍ <%= user_comments.user.username %><br>
      </div>
      <div class="col-sm-6">
        ⏱️ <%= time_ago_in_words(user_comments.created_at) %>
      </div>
    </div>
  </div>
</div>

w6-homework-serhatturkmen/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', dashboard_path %>

w6-homework-serhatturkmen/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path, class: 'btn btn-warning' %>

w6-homework-serhatturkmen/app/views/posts/show.html.erb
<div class="row">
  <div class="col-12">
    <p>
    <h1>
      <%= @post.title %>
    </h1>
    </p>
    <p>
      ✍ <%= link_to @post.user.username, user_detail_path(@post.user) %> | ⏱️<%= time_ago_in_words(@post.created_at) %>
    </p>

    <p>
      <%= @post.content %>
    </p>

    <br>
    <p> Vote(<strong id="vote_count"><%= @post.vote_count %></strong>)
      <br>
      <% if user_signed_in? && @user != current_user %>
        <%= link_to '👍', vote_add_post_path(@post), method: :patch, class: 'btn btn-primary', remote: true %>
        | <%= link_to '👎', vote_reduce_post_path(@post), method: :patch, class: 'btn btn-primary', remote: true %>
      <% end %>
    </p>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <h2>Comments</h2>
    <hr>
    <div id="user_comment">
      <% if @user_comment.any? %>
        <% @user_comment.each do |comment| %>
          <div class="card mb-5">
            <div class="card-heading text-center p-3 border">
              <b><%= comment.title %></b>
              <span class="badge badge-pill badge-success float-right">Waiting for Accept</span>
            </div>
            <div class="card-body">
              <%= comment.content %>
            </div>
            <div class="card-footer">
              <div class="row text-center">
                <div class="col-sm-6">
                  ✍ <%= comment.user.username %><br>
                </div>
                <div class="col-sm-6">
                  ⏱️ <%= time_ago_in_words(comment.created_at) %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <br>
    <% if @comments.any? %>
      <% @comments.each do |comment| %>
        <div class="card mb-5">
          <div class="card-heading text-center p-3 border">
            <b><%= comment.title %></b>
          </div>
          <div class="card-body">
            <%= comment.content %>
          </div>
          <div class="card-footer">
            <div class="row text-center">
              <div class="col-sm-6">
                ✍ <%= comment.user.username %><br>
              </div>
              <div class="col-sm-6">
                ⏱️ <%= time_ago_in_words(comment.created_at) %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="alert alert-warning">There is no comment</div>
    <% end %>

  </div>
</div>

<br>

<div class="row">
  <div class="col-12">
    <h2>Add a comment</h2>

    <div id="comment_form">
      <%= form_with(model: [@post, @post.comments.build], local: false) do |form| %>
        <p>
          <%= form.label :title %>
          <%= form.text_field :title, class: 'form-control', id: 'input_title' %>
        </p>
        <p>
          <%= form.label :content %>
          <%= form.text_area :content, class: 'form-control', id: 'textarea_content' %>
        </p>

        <p>
          <%= form.submit :class => 'form-control btn btn-primary' %>
        </p>
      <% end %>
    </div>
  </div>
</div>

<br>

<% if current_user == @post.user_id %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', _back_url %>

w6-homework-serhatturkmen/app/views/posts/vote_add.js.erb
$(document).ready(function () {
    $('#vote_count').html("<%= @post.vote_count %>");
});

w6-homework-serhatturkmen/app/views/posts/vote_reduce.js.erb
$(document).ready(function () {
    $('#vote_count').html("<%= @post.vote_count %>");
});