w6-homework-serhatturkmen/config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'
  get 'relationships/destroy'
  get 'user_detail/:id', to: 'users#show', as: 'user_detail'
  get '/feed', to: 'users#feed', as: 'user_feed'

  resources :posts do
    patch :vote_add, on: :member
    patch :vote_reduce, on: :member
    resources :comments, controller: 'comment' do
      get '/accept/:status_id', to: 'comment#accept', as: 'accept'
    end
  end
  devise_for :users

  resources :relationships, only: [:create, :destroy]

  get '/homepage', to: 'welcome#index', as: 'welcome'
  get '/dashboard', to: 'dashboard#index', as: 'dashboard'
  root 'welcome#index'
end

w6-homework-serhatturkmen/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @posts = current_user.posts.all
    @comments = []
    @posts.each do |post|
      comments_arr = post.comments
      comments_arr.each { |comment| @comments << comment }
    end
  end
end

w6-homework-serhatturkmen/app/helpers/dashboard_helper.rb
module DashboardHelper
end

w6-homework-serhatturkmen/app/views/dashboard/index.html.erb
<div class="row">
  <div class="col-sm-10">
    <h1>Posts</h1>
  </div>
  <div class="col-sm-2">
    <%= link_to 'New Post', new_post_path, class: 'btn btn-primary float-right' %>
  </div>
</div>


<% if @posts.any? %>
  <table class="table">
    <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Visible</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= substr(post.content) %></td>
        <td><%= post.visible %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-warning text-center">
    You don't have a post.
  </div>
<% end %>
<br>


<div class="row">
  <div class="col-sm-12">
    <h1>Comments</h1>
  </div>
</div>

<% if @comments.any? %>
  <table class="table">
    <thead>
    <th>Post title</th>
    <th>Title</th>
    <th>Content</th>
    <th>Created Date</th>
    <th>Visible</th>
    <th class="text-center">Comment Process</th>
    </thead>

    <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post.title %></td>
        <td><%= comment.title %></td>
        <td><%= comment.content %></td>
        <td><%= time_ago_in_words(comment.created_at) %></td>
        <td><%= comment_status_text(comment.status) %></td>
        <td class="text-center">
          <% if comment.locked %>
            Locked
          <% else %>
            <% if comment.status == 0 %>
              <%= link_to '✔', post_comment_accept_path(comment.post, comment.id, 1) %> |
              <%= link_to '❌', post_comment_accept_path(comment.post, comment.id, 2) %>
            <% elsif comment.status == 1 %>
              <%= link_to '❌', post_comment_accept_path(comment.post, comment.id, 2) %>
            <% else %>
              <%= link_to '✔', post_comment_accept_path(comment.post, comment.id, 1) %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-warning text-center">
    No Comment
  </div>
<% end %>

<br>