w6-homework-serhatturkmen/config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'
  get 'relationships/destroy'
  get 'user_detail/:id', to: 'users#show', as: 'user_detail'
  get '/feed', to: 'users#feed', as: 'user_feed'

  resources :posts do
    patch :vote_add, on: :member
    patch :vote_reduce, on: :member
    resources :comments, controller: 'comment' do
      get '/accept/:status_id', to: 'comment#accept', as: 'accept'
    end
  end
  devise_for :users

  resources :relationships, only: [:create, :destroy]

  get '/homepage', to: 'welcome#index', as: 'welcome'
  get '/dashboard', to: 'dashboard#index', as: 'dashboard'
  root 'welcome#index'
end

w6-homework-serhatturkmen/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
  validates :username, presence: true, length: { minimum: 5, maximum: 50 }
  validates :email, presence: true

  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy, inverse_of: :follower
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy, inverse_of: :followed

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(other_user)
    following << other_user unless self == other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def feed
    Post.where("user_id IN (?)", following_ids).availables
  end

end

w6-homework-serhatturkmen/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @comments = Comment.where(user_id: @user).where(status: 1)
  end

  def feed
    @posts = current_user.feed
    @users = User.all.order(created_at: :desc)
  end
end

w6-homework-serhatturkmen/app/helpers/users_helper.rb
module UsersHelper
end

w6-homework-serhatturkmen/app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, local: false) do |f| %>
  <%= hidden_field_tag :followed_id, @user.id %>
  <%= f.submit 'Follow', class: 'btn btn-primary' %>
<% end %>

w6-homework-serhatturkmen/app/views/users/_follow_form.html.erb
<div id='follow_form'>
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
</div>

w6-homework-serhatturkmen/app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
              html: { method: :delete }, local: false) do |f| %>
  <%= f.submit 'Unfollow', class: 'btn btn-primary' %>
<% end %>

w6-homework-serhatturkmen/app/views/users/feed.html.erb
<h1>DotBlog as Medium</h1>
<div class="row">
  <div class="col-sm-8">
    <% if @posts.any? %>
      <% for post in @posts %>
        <div class="jumbotron" style="padding: 10px;">
          <h2><%= link_to post.title, post_path(post.id) %></h2>
          <p>✍ <%= link_to post.user.username, user_detail_path(post.user) %> |
            ⏱️<%= time_ago_in_words(post.created_at) %> ago | 📝 <%= post.comments.accepted.count %> </p>
          <p><%= substr(post.content) %></p>
          <p>Vote: <%= post.vote_count %></p>
        </div>
      <% end %>
    <% else %>
      <div class="alert alert-warning">
        No post here. Can you add a post.
      </div>
    <% end %>
  </div>
  <div class="col-sm-4 jumbotron">
    <% if @users.count <= 1 %>
      <h3>No users other than you</h3>
    <% else %>
      <h3>New Users</h3>
      <% for user in @users %>
        <p>
          <%= link_to user.username, user_detail_path(user) %> -
          <%= user.posts.count %> posts
        </p>
      <% end %>
    <% end %>
  </div>
</div>

w6-homework-serhatturkmen/app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-1">
    <div style="border-radius: 80px;height: 80px; width: 80px;background-color: #666666;"></div>
  </div>
  <div class="col-sm-6">
    <strong>Username:</strong> <%= @user.username %>
    <br>
    <strong>Email:</strong> <%= @user.email %>
    <br>
    <strong>Registered Date:</strong> <%= time_ago_in_words(@user.created_at) %> ago
    <br>
  </div>
  <div class="col-sm-5 mb-5">
    <div id="followers">
      <strong>Follower: </strong> <%= @user.following.count %> <br>
      <strong>Following: </strong> <%= @user.followers.count %>
    </div>
    <% if user_signed_in? && @user != current_user %>
      <p><%= render 'follow_form' %></p>
    <% end %>
  </div>
  <div class="col-sm-12">
    <h2><%= @user.username %>'s posts</h2>
  </div>
  <div class="col-sm-12">
    <% if @user.posts.availables.any? %>
      <table class="table">
        <thead>
        <th>Title</th>
        <th>Content</th>
        <th>Comment</th>
        <th>Created Date</th>
        </thead>
        <tbody>
        <% for post in @user.posts.availables %>
          <tr>
            <td><%= link_to post.title, post_path(post.id) %></td>
            <td><%= substr(post.content) %></td>
            <td><%= post.comments.count %></td>
            <td><%= time_ago_in_words(post.created_at) %> ago</td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <div class="alert alert-warning">
        <%= @user.username %>'s haven't post.
      </div>
    <% end %>
  </div>
  <div class="col-sm-12">
    <h2><%= @user.username %>'s comments</h2>
  </div>
  <div class="col-sm-12">
    <% if @comments.any? %>
      <table class="table">
        <thead>
        <th>Post Title</th>
        <th>Title</th>
        <th>Content</th>
        <th>Created Date</th>
        </thead>
        <tbody>
        <% for comment in @comments %>
          <tr>
            <td><%= link_to comment.post.title, post_path(comment.post.id) %></td>
            <td><%= comment.title %></td>
            <td><%= substr(comment.content) %></td>
            <td><%= time_ago_in_words(comment.created_at) %> ago</td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <div class="alert alert-warning">
        <%= @user.username %>'s haven't comment.
      </div>
    <% end %>
  </div>
  <br>
  <%= link_to 'back', _back_url, class: 'btn btn-primary' %>
</div>